// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Garcia.CodeGenerator.Template
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using MannFramework;
    using MannFramework.CodeGenerator;
    using MannFramework.Application;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class EntityTemplate : BaseTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("/*\r\n\tThis file was generated automatically by MannFramework Framework. \r\n\tDo not " +
                    "edit manually. \r\n\tAdd a new partial class with the same name if you want to add " +
                    "extra functionality.\r\n*/");
            this.Write("\r\n");
            this.Write("using System;\r\nusing System.Collections.Generic;\r\nusing System.Data;\r\nusing Syste" +
                    "m.Linq;\r\nusing System.ComponentModel.DataAnnotations;\r\n");
            
            #line 9 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\IncludeUsings.t4"
if(FrameworkType == FrameworkType.MannFramework) { 
            
            #line default
            #line hidden
            this.Write("using MannFramework;\r\n");
            
            #line 11 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\IncludeUsings.t4"
} 
            
            #line default
            #line hidden
            
            #line 15 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"

	List<string> fields = new List<string>();

            
            #line default
            #line hidden
            this.Write("\r\nnamespace ");
            
            #line 19 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n");
            
            #line 21 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
if(Item.IsEnum) { 
            
            #line default
            #line hidden
            this.Write("\tpublic enum ");
            
            #line 22 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Item.Name));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n\t}\r\n");
            
            #line 25 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
} 
            
            #line default
            #line hidden
            
            #line 26 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
else { 
            
            #line default
            #line hidden
            this.Write("\tpublic partial class ");
            
            #line 27 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Item.Name));
            
            #line default
            #line hidden
            this.Write(" : ");
            
            #line 27 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(BaseClass));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n");
            
            #line 29 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
 
		foreach (var property in Item.Properties)
		{
			string innerTypeName = this.generator.GetInnerTypeName(property);
			string accessor = property.AccessorType.ToString().ToLowerInvariant();
			string attributes = AppendAttributes(property);
			// string accessor = "public";

            
            #line default
            #line hidden
            
            #line 37 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
if(LazyLoad && property.IsLazyLoad) { 
            
            #line default
            #line hidden
            
            #line 38 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
if(property.MappingType == ItemPropertyMappingType.Property) { 
            
            #line default
            #line hidden
            
            #line 39 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
		AppendAttributes(property); 
            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 40 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(accessor));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 40 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(innerTypeName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 40 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" { get { return Get(_");
            
            #line 40 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Id, ref _");
            
            #line 40 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("); } set { Set(ref _");
            
            #line 40 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write(", ref _");
            
            #line 40 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Id, value); } }\r\n");
            
            #line 41 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
 if(!Item.HasProperty(property.Name.ToCamelCase() + "Id")) { 
            
            #line default
            #line hidden
            this.Write("\t\t[NotSelected]\r\n        [NotSaved]\r\n\t\tpublic int? ");
            
            #line 44 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Id { get { return _");
            
            #line 44 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Id; } set { _");
            
            #line 44 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Id = value; } }\r\n");
            
            #line 45 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
} 
            
            #line default
            #line hidden
            
            #line 46 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
} 
            
            #line default
            #line hidden
            
            #line 47 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
else { 
            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 48 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attributes));
            
            #line default
            #line hidden
            
            #line 48 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(accessor));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 48 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(innerTypeName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 48 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" { get { return Get(ref _");
            
            #line 48 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("); } set { Set(ref _");
            
            #line 48 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write(", value); } }\r\n");
            
            #line 49 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
} 
            
            #line default
            #line hidden
            
            #line 49 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
} 
            
            #line default
            #line hidden
            
            #line 50 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
else if (!string.IsNullOrEmpty(property.FieldName)){ 
            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 51 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attributes));
            
            #line default
            #line hidden
            
            #line 51 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(accessor));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 51 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(innerTypeName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 51 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" { get { return ");
            
            #line 51 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.FieldName));
            
            #line default
            #line hidden
            this.Write("; } set { ");
            
            #line 51 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.FieldName));
            
            #line default
            #line hidden
            this.Write(" = value; } }\r\n");
            
            #line 52 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
} 
            
            #line default
            #line hidden
            
            #line 53 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
else { 
            
            #line default
            #line hidden
            this.Write("\t\t");
            
            #line 54 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attributes));
            
            #line default
            #line hidden
            
            #line 54 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(accessor));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 54 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(innerTypeName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 54 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n");
            
            #line 55 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
} 
            
            #line default
            #line hidden
            
            #line 56 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
 
		} 

            
            #line default
            #line hidden
            this.Write("\r\n\t\t#region Lazy load\r\n");
            
            #line 61 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"

		foreach (var property in Item.Properties)
		{
			string innerTypeName = this.generator.GetInnerTypeName(property); 
			
			if (!String.IsNullOrEmpty(property.FieldName) && !fields.Contains(property.FieldName)) 
			{
				fields.Add(property.FieldName); 
            
            #line default
            #line hidden
            this.Write("\t\tprivate ");
            
            #line 69 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(innerTypeName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 69 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.FieldName));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 70 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
} 
            
            #line default
            #line hidden
            
            #line 71 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
if(LazyLoad && property.IsLazyLoad && !fields.Contains("_" + property.Name.ToPascalCase())) { fields.Add("_" + property.Name.ToPascalCase()); 
            
            #line default
            #line hidden
            this.Write("\t\tprivate ");
            
            #line 72 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(innerTypeName));
            
            #line default
            #line hidden
            this.Write(" _");
            
            #line 72 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 73 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
if(property.MappingType == ItemPropertyMappingType.Property && !fields.Contains("_" + property.Name.ToPascalCase() + "Id")) { fields.Add("_" + property.Name.ToPascalCase() + "Id"); 
            
            #line default
            #line hidden
            this.Write("\t\tprivate int? _");
            
            #line 74 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name.ToPascalCase()));
            
            #line default
            #line hidden
            this.Write("Id;\r\n");
            
            #line 75 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
} 
            
            #line default
            #line hidden
            
            #line 76 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
else { 
            
            #line default
            #line hidden
            
            #line 77 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
} 
            
            #line default
            #line hidden
            
            #line 77 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
} 
            
            #line default
            #line hidden
            
            #line 78 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
else { 
            
            #line default
            #line hidden
            
            #line 79 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
} 
            
            #line default
            #line hidden
            
            #line 80 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
 
		}

            
            #line default
            #line hidden
            this.Write("\t\t#endregion\r\n");
            
            #line 84 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"


            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic ");
            
            #line 87 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Item.Name));
            
            #line default
            #line hidden
            this.Write("()\r\n\t\t{\r\n");
            
            #line 89 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
 
			foreach (var property in Item.Properties)
			{
				string innerTypeName = this.generator.GetInnerTypeName(property);
				
				switch (property.MappingType)
                {
                    case ItemPropertyMappingType.Property:
                        break;
                    case ItemPropertyMappingType.List: 

            
            #line default
            #line hidden
            this.Write("\t\t\tthis.");
            
            #line 100 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" = new ");
            
            #line 100 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(innerTypeName));
            
            #line default
            #line hidden
            this.Write("();\r\n");
            
            #line 101 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
						break;
                    case ItemPropertyMappingType.Array:
                        // TODO
                        break;
                }
			} 

            
            #line default
            #line hidden
            this.Write("\t\t}\r\n");
            
            #line 109 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
 
	List<ItemProperty> toStringProperties = Item.Properties.Where(x => x.AppendToToString).ToList();
	
	if (toStringProperties.Count != 0)
	{

            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic override string ToString()\r\n\t\t{\r\n");
            
            #line 118 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"

			if (toStringProperties.Count == 1)
			{
				string builder = "this." + toStringProperties[0].Name;

				if (toStringProperties[0].Type != ItemPropertyType.String)
				{
					builder += ".ToString()";
				}


            
            #line default
            #line hidden
            this.Write("\t\t\treturn ");
            
            #line 129 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(builder));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t}\r\n");
            
            #line 131 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"

			}
			else
			{
				int index = 0;
				string builder = "new MannFrameworkStringBuilder(' ', ";

				foreach(var property in toStringProperties)
				{
					builder += "this.";
					builder += property.Name;

					if (property.Type != ItemPropertyType.String)
					{
						builder += ".ToString()";
					}

					if (index != toStringProperties.Count - 1)
					{
						builder += ", ";
					}
					else
					{
						builder += ").ToString()";
					}

					index++;
				}

            
            #line default
            #line hidden
            this.Write("\t\t\treturn ");
            
            #line 160 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(builder));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t}\r\n");
            
            #line 162 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"

		}
	}

            
            #line default
            #line hidden
            this.Write("\t}\r\n");
            
            #line 167 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"
} 
            
            #line default
            #line hidden
            this.Write("}\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 170 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"

	protected override Generator CreateGenerator()
	{
		return new EntityGenerator();
	}

	protected string AppendAttributes(ItemProperty property)
	{
		string attributes = "";

		if (property.NotSaved)
		{
			attributes += "[NotSaved]\n\t\t";
		}

		if (property.NotSelected)
		{
			attributes += "[NotSelected]\n\t\t";
		}

		if (property.MvcIgnore)
		{
			attributes += "[MvcIgnore]\n\t\t";
		}

		if (property.MvcListIgnore)
		{
			attributes += "[MvcListIgnore]\n\t\t";
		}

		if (!property.IsNullable)
		{
			attributes += "[Required]\n\t\t";
		}

		switch (property.Type)
		{
			case ItemPropertyType.String:
				if (property.MaxLength != 0)
				{
					attributes += "[StringLength(" + property.MaxLength.ToString() + ", MinimumLength = " + property.MinLength.ToString() + ")]\n\t\t";
				}
				break;
			case ItemPropertyType.Double:
			case ItemPropertyType.Float:
			case ItemPropertyType.Decimal:
				if (property.MinLength != 0 && property.MaxLength != 0)
				{
					attributes += "[Range(" + property.MinLength.ToString() + ", " + property.MaxLength.ToString() + ")]\n\t\t";
				}
				break;
		}

		if (!string.IsNullOrEmpty(property.RegularExpressionValidation))
		{
			attributes += "[RegularExpression(\"@" + property.RegularExpressionValidation + "\")]\n\t\t";
		}

		// return attributes.TrimEnd('\n');
		return attributes;
	}

        
        #line default
        #line hidden
        
        #line 1 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\EntityTemplate.tt"

private global::MannFramework.Application.Item _ItemField;

/// <summary>
/// Access the Item parameter of the template.
/// </summary>
private global::MannFramework.Application.Item Item
{
    get
    {
        return this._ItemField;
    }
}

private string _BaseClassField;

/// <summary>
/// Access the BaseClass parameter of the template.
/// </summary>
private string BaseClass
{
    get
    {
        return this._BaseClassField;
    }
}

private string _NamespaceField;

/// <summary>
/// Access the Namespace parameter of the template.
/// </summary>
private string Namespace
{
    get
    {
        return this._NamespaceField;
    }
}

private bool _LazyLoadField;

/// <summary>
/// Access the LazyLoad parameter of the template.
/// </summary>
private bool LazyLoad
{
    get
    {
        return this._LazyLoadField;
    }
}

private global::MannFramework.Application.FrameworkType _FrameworkTypeField;

/// <summary>
/// Access the FrameworkType parameter of the template.
/// </summary>
private global::MannFramework.Application.FrameworkType FrameworkType
{
    get
    {
        return this._FrameworkTypeField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public override void Initialize()
{
    base.Initialize();
    if ((this.Errors.HasErrors == false))
    {
bool ItemValueAcquired = false;
if (this.Session.ContainsKey("Item"))
{
    this._ItemField = ((global::MannFramework.Application.Item)(this.Session["Item"]));
    ItemValueAcquired = true;
}
if ((ItemValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Item");
    if ((data != null))
    {
        this._ItemField = ((global::MannFramework.Application.Item)(data));
    }
}
bool BaseClassValueAcquired = false;
if (this.Session.ContainsKey("BaseClass"))
{
    this._BaseClassField = ((string)(this.Session["BaseClass"]));
    BaseClassValueAcquired = true;
}
if ((BaseClassValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("BaseClass");
    if ((data != null))
    {
        this._BaseClassField = ((string)(data));
    }
}
bool NamespaceValueAcquired = false;
if (this.Session.ContainsKey("Namespace"))
{
    this._NamespaceField = ((string)(this.Session["Namespace"]));
    NamespaceValueAcquired = true;
}
if ((NamespaceValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Namespace");
    if ((data != null))
    {
        this._NamespaceField = ((string)(data));
    }
}
bool LazyLoadValueAcquired = false;
if (this.Session.ContainsKey("LazyLoad"))
{
    this._LazyLoadField = ((bool)(this.Session["LazyLoad"]));
    LazyLoadValueAcquired = true;
}
if ((LazyLoadValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("LazyLoad");
    if ((data != null))
    {
        this._LazyLoadField = ((bool)(data));
    }
}
bool FrameworkTypeValueAcquired = false;
if (this.Session.ContainsKey("FrameworkType"))
{
    this._FrameworkTypeField = ((global::MannFramework.Application.FrameworkType)(this.Session["FrameworkType"]));
    FrameworkTypeValueAcquired = true;
}
if ((FrameworkTypeValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("FrameworkType");
    if ((data != null))
    {
        this._FrameworkTypeField = ((global::MannFramework.Application.FrameworkType)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
