// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Garcia.CodeGenerator.Template
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using MannFramework.CodeGenerator;
    using MannFramework.Application;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MssqlTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class MssqlTemplate : BaseTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("\r\ncreate table ");
            
            #line 14 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MssqlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Item.Name));
            
            #line default
            #line hidden
            this.Write("\r\n(\r\n\t[Id] int primary key identity (1, 1),\r\n");
            
            #line 17 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MssqlTemplate.tt"
	if (UseInsertTime)
	{

            
            #line default
            #line hidden
            this.Write("\t[InsertTime] datetime not null default (getdate()),\r\n");
            
            #line 21 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MssqlTemplate.tt"

	}
	if (UseDeleteTime)
	{

            
            #line default
            #line hidden
            this.Write("\t[DeleteTime] datetime,\r\n");
            
            #line 27 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MssqlTemplate.tt"

	}

	int index = -1;
	List<ItemProperty> properties = Item.Properties.Where(x => x.MappingType == ItemPropertyMappingType.Property).ToList();
	string alterCommands = "";
	string alterAddCommands = "";

	foreach (var property in properties)
	{
		index++;
		string columnType = this.generator.GetInnerTypeName(property); 
		string columnName = "[" + property.Name;

		if (property.Type == ItemPropertyType.Class)
		{
			columnName = columnName + "Id";

			if (GenerateForeignKeyConstraint)
			{
				string propertyName = property.InnerType != null ? property.InnerType.Name : property.Name;
				columnType += " foreign key references " + propertyName + "(Id)";
			}
		}

		columnName += "]";
		alterAddCommands += "alter table " + Item.Name + " add " + columnName + " " + columnType + "\n" ;
		alterCommands += "alter table " + Item.Name + " alter column " + columnName + " " + columnType + "\n" ;

            
            #line default
            #line hidden
            this.Write("\t");
            
            #line 56 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MssqlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(columnName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 56 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MssqlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(columnType));
            
            #line default
            #line hidden
            
            #line 56 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MssqlTemplate.tt"
 if (index != properties.Count - 1){
            
            #line default
            #line hidden
            this.Write(",\r\n");
            
            #line 57 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MssqlTemplate.tt"
}
	}

            
            #line default
            #line hidden
            this.Write("\r\n)\r\ngo\r\n\r\n");
            
            #line 64 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MssqlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(alterAddCommands));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 66 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MssqlTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(alterCommands));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            
            #line 68 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MssqlTemplate.tt"

	if (GenerateStoredProcedures)
	{
	}

            
            #line default
            #line hidden
            this.Write("\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 74 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MssqlTemplate.tt"

	protected override Generator CreateGenerator()
	{
		return new MssqlGenerator();
	}

        
        #line default
        #line hidden
        
        #line 1 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MssqlTemplate.tt"

private global::MannFramework.Application.Item _ItemField;

/// <summary>
/// Access the Item parameter of the template.
/// </summary>
private global::MannFramework.Application.Item Item
{
    get
    {
        return this._ItemField;
    }
}

private bool _GenerateForeignKeyConstraintField;

/// <summary>
/// Access the GenerateForeignKeyConstraint parameter of the template.
/// </summary>
private bool GenerateForeignKeyConstraint
{
    get
    {
        return this._GenerateForeignKeyConstraintField;
    }
}

private bool _GenerateStoredProceduresField;

/// <summary>
/// Access the GenerateStoredProcedures parameter of the template.
/// </summary>
private bool GenerateStoredProcedures
{
    get
    {
        return this._GenerateStoredProceduresField;
    }
}

private bool _UseInsertTimeField;

/// <summary>
/// Access the UseInsertTime parameter of the template.
/// </summary>
private bool UseInsertTime
{
    get
    {
        return this._UseInsertTimeField;
    }
}

private bool _UseDeleteTimeField;

/// <summary>
/// Access the UseDeleteTime parameter of the template.
/// </summary>
private bool UseDeleteTime
{
    get
    {
        return this._UseDeleteTimeField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public override void Initialize()
{
    base.Initialize();
    if ((this.Errors.HasErrors == false))
    {
bool ItemValueAcquired = false;
if (this.Session.ContainsKey("Item"))
{
    this._ItemField = ((global::MannFramework.Application.Item)(this.Session["Item"]));
    ItemValueAcquired = true;
}
if ((ItemValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Item");
    if ((data != null))
    {
        this._ItemField = ((global::MannFramework.Application.Item)(data));
    }
}
bool GenerateForeignKeyConstraintValueAcquired = false;
if (this.Session.ContainsKey("GenerateForeignKeyConstraint"))
{
    this._GenerateForeignKeyConstraintField = ((bool)(this.Session["GenerateForeignKeyConstraint"]));
    GenerateForeignKeyConstraintValueAcquired = true;
}
if ((GenerateForeignKeyConstraintValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("GenerateForeignKeyConstraint");
    if ((data != null))
    {
        this._GenerateForeignKeyConstraintField = ((bool)(data));
    }
}
bool GenerateStoredProceduresValueAcquired = false;
if (this.Session.ContainsKey("GenerateStoredProcedures"))
{
    this._GenerateStoredProceduresField = ((bool)(this.Session["GenerateStoredProcedures"]));
    GenerateStoredProceduresValueAcquired = true;
}
if ((GenerateStoredProceduresValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("GenerateStoredProcedures");
    if ((data != null))
    {
        this._GenerateStoredProceduresField = ((bool)(data));
    }
}
bool UseInsertTimeValueAcquired = false;
if (this.Session.ContainsKey("UseInsertTime"))
{
    this._UseInsertTimeField = ((bool)(this.Session["UseInsertTime"]));
    UseInsertTimeValueAcquired = true;
}
if ((UseInsertTimeValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("UseInsertTime");
    if ((data != null))
    {
        this._UseInsertTimeField = ((bool)(data));
    }
}
bool UseDeleteTimeValueAcquired = false;
if (this.Session.ContainsKey("UseDeleteTime"))
{
    this._UseDeleteTimeField = ((bool)(this.Session["UseDeleteTime"]));
    UseDeleteTimeValueAcquired = true;
}
if ((UseDeleteTimeValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("UseDeleteTime");
    if ((data != null))
    {
        this._UseDeleteTimeField = ((bool)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
