// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Garcia.CodeGenerator.Template
{
    using System.Linq;
    using System.Text;
    using System.Web;
    using System.Web.Mvc;
    using System.Collections.Generic;
    using MannFramework;
    using MannFramework.Application;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcControllerTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class MvcControllerTemplate : BaseTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("/*\r\n\tThis file was generated automatically by MannFramework Framework. \r\n\tDo not " +
                    "edit manually. \r\n\tAdd a new partial class with the same name if you want to add " +
                    "extra functionality.\r\n*/");
            this.Write("\r\n");
            this.Write("using System;\r\nusing System.Collections.Generic;\r\nusing System.Data;\r\nusing Syste" +
                    "m.Linq;\r\nusing System.ComponentModel.DataAnnotations;\r\n");
            
            #line 9 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\IncludeUsings.t4"
if(FrameworkType == FrameworkType.MannFramework) { 
            
            #line default
            #line hidden
            this.Write("using MannFramework;\r\n");
            
            #line 11 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\IncludeUsings.t4"
} 
            
            #line default
            #line hidden
            this.Write("  \r\n");
            
            #line 22 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcControllerTemplate.tt"

	string itemName = Item.Name;
	string modelName = itemName;

	if (GenerateMvcModel)
	{
		modelName += "Model";
	}

	string controllerName = itemName + "Controller";
	string listMethod = "";
	string getOneMethod = "";
	string postMethod = "";
	string deleteMethod = "";

	if (GenerateMvcModel)
	{
		listMethod = "MannFrameworkHttpResponseMessage<List<" + modelName + ">> models = this.GetModels();";
		getOneMethod = "MannFrameworkHttpResponseMessage<" + modelName + "> model = this.GetModel(id);";
	}
	else
	{
		listMethod = "List<" + modelName + "> models = EntityManager.Instance.GetItems<" + modelName + ">();";
		getOneMethod = modelName + " model = EntityManager.Instance.GetItem<" + modelName + ">(id);";
	}

	string className = "public partial class " + itemName + "Controller : " + BaseMvcControllerName + "<" + itemName;
	
	if (GenerateMvcModel)
	{
		className += (", " + modelName);
	}
	
	className += ">";

            
            #line default
            #line hidden
            this.Write("using System.Web.Mvc;\r\n");
            
            #line 58 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Includes));
            
            #line default
            #line hidden
            this.Write("\r\nnamespace ");
            
            #line 59 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n\t");
            
            #line 61 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n");
            
            #line 63 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcControllerTemplate.tt"
if(GenerateGetOne) { 
            
            #line default
            #line hidden
            this.Write("\t\t[HttpGet]\r\n\t\tpublic override ActionResult Edit(int id)\r\n        {\r\n            " +
                    "");
            
            #line 67 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(getOneMethod));
            
            #line default
            #line hidden
            this.Write("\r\n            return View(model);\r\n        }\r\n\r\n");
            
            #line 71 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcControllerTemplate.tt"
} 
            
            #line default
            #line hidden
            
            #line 72 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcControllerTemplate.tt"
if(GenerateGetAll) { 
            
            #line default
            #line hidden
            this.Write("\t\t[HttpGet]\r\n\t\tpublic override ActionResult Index()\r\n        {\r\n            ");
            
            #line 76 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(listMethod));
            
            #line default
            #line hidden
            this.Write("\r\n            return View(models);\r\n        }\r\n\r\n");
            
            #line 80 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcControllerTemplate.tt"
} 
            
            #line default
            #line hidden
            
            #line 81 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcControllerTemplate.tt"
if(GeneratePost) { 
            
            #line default
            #line hidden
            this.Write("\t\t[HttpPost]\r\n\t\tpublic override ActionResult Edit(");
            
            #line 83 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelName));
            
            #line default
            #line hidden
            this.Write(" model)\r\n        {\r\n\t\t\tif (ModelState.IsValid)\r\n            {\r\n");
            
            #line 87 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcControllerTemplate.tt"
if(GenerateMvcModel) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t");
            
            #line 88 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(itemName));
            
            #line default
            #line hidden
            this.Write(@" item = model.ToEntity();

				if (item == null)
				{
					return new MannFrameworkHttpResponseMessage(System.Net.HttpStatusCode.NotFound);
				}

				OperationResult saveResult = EntityManager.Instance.Save(item);
				
				if (saveResult.Success)
                {
                    return RedirectToAction(""Index"");
                }
");
            
            #line 101 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcControllerTemplate.tt"
} else { 
            
            #line default
            #line hidden
            this.Write("                OperationResult saveResult = EntityManager.Instance.Save(model);\r" +
                    "\n\r\n                if (saveResult.Success)\r\n                {\r\n                 " +
                    "   return RedirectToAction(\"Index\");\r\n                }\r\n");
            
            #line 108 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcControllerTemplate.tt"
} 
            
            #line default
            #line hidden
            this.Write("\t\t\t}\r\n\r\n            return View(model);\r\n        }\r\n\r\n");
            
            #line 114 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcControllerTemplate.tt"
} 
            
            #line default
            #line hidden
            
            #line 115 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcControllerTemplate.tt"
if(GenerateDelete) { 
            
            #line default
            #line hidden
            this.Write("\t\t[HttpDelete]\r\n\t\tpublic override MannFrameworkHttpResponseMessage<");
            
            #line 117 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelName));
            
            #line default
            #line hidden
            this.Write("> Delete(int id)\r\n        {\r\n            ");
            
            #line 119 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(itemName));
            
            #line default
            #line hidden
            this.Write(" item = EntityManager.Instance.GetItem<");
            
            #line 119 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(itemName));
            
            #line default
            #line hidden
            this.Write(">(id);\r\n            item.IsMarkedForDeletion = true;\r\n            OperationResult" +
                    " result = EntityManager.Instance.Save(item);\r\n            return new MannFramewo" +
                    "rkHttpResponseMessage<");
            
            #line 122 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelName));
            
            #line default
            #line hidden
            this.Write(">(result);\r\n        }\r\n\r\n");
            
            #line 125 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcControllerTemplate.tt"
} 
            
            #line default
            #line hidden
            
            #line 126 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcControllerTemplate.tt"
if(GenerateInnerGet) {
		foreach (var property in Item.Properties)
		{
			if (property.InnerType == null)
			{
				continue;
			}

			string innerTypeName = this.generator.GetInnerTypeName(property); 

			switch (property.MappingType)
            {
                case ItemPropertyMappingType.Property: 
                    break;
                case ItemPropertyMappingType.List: 
            
            #line default
            #line hidden
            this.Write("\t\t\r\n\t\t[HttpGet]\r\n\t\tpublic MannFrameworkHttpResponseMessage<List<");
            
            #line 143 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.InnerType.Name));
            
            #line default
            #line hidden
            this.Write("Model>> ");
            
            #line 143 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write("(int id)\r\n\t\t{\r\n\t\t\tMannFrameworkHttpResponseMessage<");
            
            #line 145 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelName));
            
            #line default
            #line hidden
            this.Write("> model = this.GetModel(id);\r\n\t\t\tList<");
            
            #line 146 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.InnerType.Name));
            
            #line default
            #line hidden
            this.Write("Model> models = ModelBase.GetModels<");
            
            #line 146 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.InnerType.Name));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 146 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.InnerType.Name));
            
            #line default
            #line hidden
            this.Write("Model>(");
            
            #line 146 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n\t\t\treturn models;\r\n\t\t}\r\n");
            
            #line 149 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcControllerTemplate.tt"

					break;
                case ItemPropertyMappingType.Array:
                    // TODO
                    break;
            }
		}
} 
            
            #line default
            #line hidden
            this.Write("\t}\r\n}\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 160 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcControllerTemplate.tt"

	protected override Generator CreateGenerator()
	{
		return new WebApiControllerGenerator();
	}

        
        #line default
        #line hidden
        
        #line 1 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcControllerTemplate.tt"

private global::MannFramework.Application.Item _ItemField;

/// <summary>
/// Access the Item parameter of the template.
/// </summary>
private global::MannFramework.Application.Item Item
{
    get
    {
        return this._ItemField;
    }
}

private bool _GenerateGetOneField;

/// <summary>
/// Access the GenerateGetOne parameter of the template.
/// </summary>
private bool GenerateGetOne
{
    get
    {
        return this._GenerateGetOneField;
    }
}

private bool _GenerateGetAllField;

/// <summary>
/// Access the GenerateGetAll parameter of the template.
/// </summary>
private bool GenerateGetAll
{
    get
    {
        return this._GenerateGetAllField;
    }
}

private bool _GeneratePostField;

/// <summary>
/// Access the GeneratePost parameter of the template.
/// </summary>
private bool GeneratePost
{
    get
    {
        return this._GeneratePostField;
    }
}

private bool _GenerateDeleteField;

/// <summary>
/// Access the GenerateDelete parameter of the template.
/// </summary>
private bool GenerateDelete
{
    get
    {
        return this._GenerateDeleteField;
    }
}

private bool _GenerateInnerGetField;

/// <summary>
/// Access the GenerateInnerGet parameter of the template.
/// </summary>
private bool GenerateInnerGet
{
    get
    {
        return this._GenerateInnerGetField;
    }
}

private string _BaseMvcControllerNameField;

/// <summary>
/// Access the BaseMvcControllerName parameter of the template.
/// </summary>
private string BaseMvcControllerName
{
    get
    {
        return this._BaseMvcControllerNameField;
    }
}

private bool _GenerateMvcModelField;

/// <summary>
/// Access the GenerateMvcModel parameter of the template.
/// </summary>
private bool GenerateMvcModel
{
    get
    {
        return this._GenerateMvcModelField;
    }
}

private string _NamespaceField;

/// <summary>
/// Access the Namespace parameter of the template.
/// </summary>
private string Namespace
{
    get
    {
        return this._NamespaceField;
    }
}

private string _IncludesField;

/// <summary>
/// Access the Includes parameter of the template.
/// </summary>
private string Includes
{
    get
    {
        return this._IncludesField;
    }
}

private global::MannFramework.Application.FrameworkType _FrameworkTypeField;

/// <summary>
/// Access the FrameworkType parameter of the template.
/// </summary>
private global::MannFramework.Application.FrameworkType FrameworkType
{
    get
    {
        return this._FrameworkTypeField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public override void Initialize()
{
    base.Initialize();
    if ((this.Errors.HasErrors == false))
    {
bool ItemValueAcquired = false;
if (this.Session.ContainsKey("Item"))
{
    this._ItemField = ((global::MannFramework.Application.Item)(this.Session["Item"]));
    ItemValueAcquired = true;
}
if ((ItemValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Item");
    if ((data != null))
    {
        this._ItemField = ((global::MannFramework.Application.Item)(data));
    }
}
bool GenerateGetOneValueAcquired = false;
if (this.Session.ContainsKey("GenerateGetOne"))
{
    this._GenerateGetOneField = ((bool)(this.Session["GenerateGetOne"]));
    GenerateGetOneValueAcquired = true;
}
if ((GenerateGetOneValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("GenerateGetOne");
    if ((data != null))
    {
        this._GenerateGetOneField = ((bool)(data));
    }
}
bool GenerateGetAllValueAcquired = false;
if (this.Session.ContainsKey("GenerateGetAll"))
{
    this._GenerateGetAllField = ((bool)(this.Session["GenerateGetAll"]));
    GenerateGetAllValueAcquired = true;
}
if ((GenerateGetAllValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("GenerateGetAll");
    if ((data != null))
    {
        this._GenerateGetAllField = ((bool)(data));
    }
}
bool GeneratePostValueAcquired = false;
if (this.Session.ContainsKey("GeneratePost"))
{
    this._GeneratePostField = ((bool)(this.Session["GeneratePost"]));
    GeneratePostValueAcquired = true;
}
if ((GeneratePostValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("GeneratePost");
    if ((data != null))
    {
        this._GeneratePostField = ((bool)(data));
    }
}
bool GenerateDeleteValueAcquired = false;
if (this.Session.ContainsKey("GenerateDelete"))
{
    this._GenerateDeleteField = ((bool)(this.Session["GenerateDelete"]));
    GenerateDeleteValueAcquired = true;
}
if ((GenerateDeleteValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("GenerateDelete");
    if ((data != null))
    {
        this._GenerateDeleteField = ((bool)(data));
    }
}
bool GenerateInnerGetValueAcquired = false;
if (this.Session.ContainsKey("GenerateInnerGet"))
{
    this._GenerateInnerGetField = ((bool)(this.Session["GenerateInnerGet"]));
    GenerateInnerGetValueAcquired = true;
}
if ((GenerateInnerGetValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("GenerateInnerGet");
    if ((data != null))
    {
        this._GenerateInnerGetField = ((bool)(data));
    }
}
bool BaseMvcControllerNameValueAcquired = false;
if (this.Session.ContainsKey("BaseMvcControllerName"))
{
    this._BaseMvcControllerNameField = ((string)(this.Session["BaseMvcControllerName"]));
    BaseMvcControllerNameValueAcquired = true;
}
if ((BaseMvcControllerNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("BaseMvcControllerName");
    if ((data != null))
    {
        this._BaseMvcControllerNameField = ((string)(data));
    }
}
bool GenerateMvcModelValueAcquired = false;
if (this.Session.ContainsKey("GenerateMvcModel"))
{
    this._GenerateMvcModelField = ((bool)(this.Session["GenerateMvcModel"]));
    GenerateMvcModelValueAcquired = true;
}
if ((GenerateMvcModelValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("GenerateMvcModel");
    if ((data != null))
    {
        this._GenerateMvcModelField = ((bool)(data));
    }
}
bool NamespaceValueAcquired = false;
if (this.Session.ContainsKey("Namespace"))
{
    this._NamespaceField = ((string)(this.Session["Namespace"]));
    NamespaceValueAcquired = true;
}
if ((NamespaceValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Namespace");
    if ((data != null))
    {
        this._NamespaceField = ((string)(data));
    }
}
bool IncludesValueAcquired = false;
if (this.Session.ContainsKey("Includes"))
{
    this._IncludesField = ((string)(this.Session["Includes"]));
    IncludesValueAcquired = true;
}
if ((IncludesValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Includes");
    if ((data != null))
    {
        this._IncludesField = ((string)(data));
    }
}
bool FrameworkTypeValueAcquired = false;
if (this.Session.ContainsKey("FrameworkType"))
{
    this._FrameworkTypeField = ((global::MannFramework.Application.FrameworkType)(this.Session["FrameworkType"]));
    FrameworkTypeValueAcquired = true;
}
if ((FrameworkTypeValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("FrameworkType");
    if ((data != null))
    {
        this._FrameworkTypeField = ((global::MannFramework.Application.FrameworkType)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
