// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Garcia.CodeGenerator.Template
{
    using MannFramework;
    using MannFramework.Application;
    using System;
    using System.Collections.Generic;
    using System.Linq;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class MvcEditViewTemplate : BaseTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            
            #line 12 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"

	string itemName = Item.Name;
	string modelName = itemName;

	if (GenerateMvcModel)
	{
		modelName += "Model";
	}

	string controllerName = itemName + "Controller";
	string viewName = "Edit";
	List<ItemProperty> properties = Item.Properties.Where(x => !x.MvcIgnore).ToList();
	string actionLinks = GetActionLinks(properties);
	properties = properties.Where(x => x.MappingType != ItemPropertyMappingType.List).ToList();
	var groups = properties.GroupBy(x => x.EditGroupName);
	string clientSideControllerName = UseAngular2 ? " ng-controller=\"" + itemName + "Ctrl\"" : "";
	string clientSideInitFunction = UseAngular2 ? " ng-init=\"InitEdit()\"" : "";

            
            #line default
            #line hidden
            this.Write("@model ");
            
            #line 30 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelName));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n<div class=\"wrapper wrapper-content animated fadeInRight\"");
            
            #line 32 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(clientSideControllerName));
            
            #line default
            #line hidden
            this.Write(">\r\n    <div class=\"row\"");
            
            #line 33 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(clientSideInitFunction));
            
            #line default
            #line hidden
            this.Write(">\r\n        <div class=\"col-lg-12\">\r\n            <div class=\"ibox float-e-margins\"" +
                    ">\r\n\t\t\t\t@using (Html.BeginForm())\r\n\t\t\t\t{\r\n\t\t\t\t\t<div class=\"ibox-title\">  \r\n\t\t\t\t\t\t" +
                    "<h5>@Html.EditPageTitle(\"");
            
            #line 39 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(itemName));
            
            #line default
            #line hidden
            this.Write("\")</h5>\r\n");
            
            #line 40 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
 if (AddSaveLinksToTop) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t<div class=\"ibox-tools\">\r\n");
            
            #line 42 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
 if (!string.IsNullOrEmpty(actionLinks)) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t");
            
            #line 43 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(actionLinks));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 44 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t@Html.SaveLinks()\r\n\t\t\t\t\t\t</div>\r\n");
            
            #line 47 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t</div>\r\n\t\t\t\t\t<div class=\"ibox-content\">\r\n\t\t\t\t\t\t@Html.AntiForgeryToken()\r\n\t\t\t" +
                    "\t\t\t\t<div class=\"form-horizontal\">\r\n\t\t\t\t\t\t\t\t@Html.ValidationSummary(true)\r\n");
            
            #line 53 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
 foreach(var group in groups) { int propertyCount = group.Count(); int counter = 0; 
            
            #line default
            #line hidden
            
            #line 54 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
 if (!string.IsNullOrEmpty(group.Key)) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t<h4>@Html.Localize(\"");
            
            #line 55 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(group.Key));
            
            #line default
            #line hidden
            this.Write("\")</h4>\r\n");
            
            #line 56 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
 } foreach (var property in group) { 
            
            #line default
            #line hidden
            
            #line 57 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
 if (property.Name == "Id") { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t@Html.HiddenFor(model => model.");
            
            #line 58 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n");
            
            #line 59 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
} 
            
            #line default
            #line hidden
            
            #line 60 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
 else { 
            
            #line default
            #line hidden
            
            #line 61 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
 if (counter % ItemInRowCount == 0) {
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n");
            
            #line 63 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t\t<div class=\"col-md-2\">\r\n\t\t\t\t\t\t\t\t\t\t@Html.LocalizedStyledLabel(\"");
            
            #line 65 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(itemName));
            
            #line default
            #line hidden
            this.Write(".");
            
            #line 65 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write("\")\r\n\t\t\t\t\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t\t<div class=\"");
            
            #line 67 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(GetRowClass()));
            
            #line default
            #line hidden
            this.Write("\">\r\n");
            
            #line 68 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
 if (property.MappingType == ItemPropertyMappingType.Property) { 
            
            #line default
            #line hidden
            
            #line 69 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
 if (property.InnerType == null) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t\t\t@Html.EditorFor(model => model.");
            
            #line 70 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n");
            
            #line 71 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
} else if (property.Type == ItemPropertyType.Enum){
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t\t\t@Html.StyledDropDownListForEnum(\"");
            
            #line 72 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write("\", typeof(");
            
            #line 72 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.InnerType.Name));
            
            #line default
            #line hidden
            this.Write("), Model.");
            
            #line 72 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n");
            
            #line 73 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
} else {
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t\t\t@Html.StyledDropDownList(\"");
            
            #line 74 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write("Id\", Html.GetItems<");
            
            #line 74 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.InnerType.Name));
            
            #line default
            #line hidden
            this.Write(">(), Model.");
            
            #line 74 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write("Id)\r\n");
            
            #line 75 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
} 
            
            #line default
            #line hidden
            
            #line 76 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
} else if (property.AssociationType == AssociationType.Aggregation){ 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t\t\t@Html.StyledListBox(\"");
            
            #line 77 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write("\", Model.");
            
            #line 77 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(".ToSelectList())\r\n");
            
            #line 78 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
} else {
            
            #line default
            #line hidden
            
            #line 79 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
} 
            
            #line default
            #line hidden
            
            #line 80 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
} 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t\t\t@Html.ValidationMessageFor(model => model.");
            
            #line 81 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t\t\t\t\t\t\t\t</div> ");
            
            #line 82 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(WriteComment("GetRowClass()")));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 83 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
 if (counter % ItemInRowCount == ItemInRowCount - 1 || counter == propertyCount - 1) {
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t</div> ");
            
            #line 84 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(WriteComment("form-group")));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 85 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 86 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
 counter++; 
            
            #line default
            #line hidden
            
            #line 87 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
} 
            
            #line default
            #line hidden
            
            #line 88 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
} 
            
            #line default
            #line hidden
            
            #line 89 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
 if (AddSaveLinksToBottom) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t\t<div class=\"hr-line-dashed\"></div>\r\n\t\t\t\t\t\t\t\t<div class=\"form-group\">\r\n\t\t\t" +
                    "\t\t\t\t\t\t<div class=\"col-md-offset-10 col-md-2\">\r\n\t\t\t\t\t\t\t\t\t\t@Html.SaveLinks()\r\n\t\t\t\t" +
                    "\t\t\t\t\t</div>\r\n\t\t\t\t\t\t\t\t</div> ");
            
            #line 95 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(WriteComment("form-group")));
            
            #line default
            #line hidden
            this.Write("\r\n");
            
            #line 96 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
} 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t\t\t\t</div> ");
            
            #line 97 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(WriteComment("form-horizontal")));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t\t</div> ");
            
            #line 98 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(WriteComment("ibox-content")));
            
            #line default
            #line hidden
            this.Write("\r\n\t\t\t\t}\r\n            </div> ");
            
            #line 100 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(WriteComment("ibox")));
            
            #line default
            #line hidden
            this.Write("\r\n        </div> ");
            
            #line 101 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(WriteComment("col-lg-12")));
            
            #line default
            #line hidden
            this.Write("\r\n    </div> ");
            
            #line 102 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(WriteComment("row")));
            
            #line default
            #line hidden
            this.Write("\r\n </div> ");
            
            #line 103 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(WriteComment("wrapper")));
            
            #line default
            #line hidden
            this.Write("\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 105 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"

	protected string WriteComment(string comment)
	{
		bool debug = false;
		return debug ? "<!--" + comment + "-->" : "";
	}

	protected string GetRowClass()
	{
		if (ItemInRowCount == 1)
		{
			return "col-md-10";
		}
		else if (ItemInRowCount == 2)
		{
			return "col-md-4";
		}
		else
		{
			return "";
		}
	}

	protected string GetActionLinks(List<ItemProperty> properties)
	{
		var temp = properties.Where(x => x.MappingType != ItemPropertyMappingType.Property && x.AssociationType != AssociationType.Aggregation).ToList();
		string actionLinks = "";
		int counter = 0;

		foreach(ItemProperty property in temp)
		{
			string actionLink = "@Html.LocalizedStyledActionLinkForExistingItem(\"" + property.Name + "\", \"List\", \"" + property.InnerType.Name + "\", new RouteValueDictionary () { { \"" + Item.Name + "Id\", Model.Id } })";
			actionLinks += actionLink;

			if (counter != temp.Count - 1)
			{
				actionLinks += "\n\t\t\t\t\t\t\t";
				counter++;
			}
		}

		return actionLinks;
	}

        
        #line default
        #line hidden
        
        #line 1 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\MvcEditViewTemplate.tt"

private global::MannFramework.Application.Item _ItemField;

/// <summary>
/// Access the Item parameter of the template.
/// </summary>
private global::MannFramework.Application.Item Item
{
    get
    {
        return this._ItemField;
    }
}

private int _ItemInRowCountField;

/// <summary>
/// Access the ItemInRowCount parameter of the template.
/// </summary>
private int ItemInRowCount
{
    get
    {
        return this._ItemInRowCountField;
    }
}

private bool _GenerateMvcModelField;

/// <summary>
/// Access the GenerateMvcModel parameter of the template.
/// </summary>
private bool GenerateMvcModel
{
    get
    {
        return this._GenerateMvcModelField;
    }
}

private bool _UseAngular2Field;

/// <summary>
/// Access the UseAngular2 parameter of the template.
/// </summary>
private bool UseAngular2
{
    get
    {
        return this._UseAngular2Field;
    }
}

private bool _AddSaveLinksToTopField;

/// <summary>
/// Access the AddSaveLinksToTop parameter of the template.
/// </summary>
private bool AddSaveLinksToTop
{
    get
    {
        return this._AddSaveLinksToTopField;
    }
}

private bool _AddSaveLinksToBottomField;

/// <summary>
/// Access the AddSaveLinksToBottom parameter of the template.
/// </summary>
private bool AddSaveLinksToBottom
{
    get
    {
        return this._AddSaveLinksToBottomField;
    }
}

private string _ViewDataTypeNameField;

/// <summary>
/// Access the ViewDataTypeName parameter of the template.
/// </summary>
private string ViewDataTypeName
{
    get
    {
        return this._ViewDataTypeNameField;
    }
}

private string _ViewDataTypeShortNameField;

/// <summary>
/// Access the ViewDataTypeShortName parameter of the template.
/// </summary>
private string ViewDataTypeShortName
{
    get
    {
        return this._ViewDataTypeShortNameField;
    }
}

private bool _IsPartialViewField;

/// <summary>
/// Access the IsPartialView parameter of the template.
/// </summary>
private bool IsPartialView
{
    get
    {
        return this._IsPartialViewField;
    }
}

private bool _IsLayoutPageSelectedField;

/// <summary>
/// Access the IsLayoutPageSelected parameter of the template.
/// </summary>
private bool IsLayoutPageSelected
{
    get
    {
        return this._IsLayoutPageSelectedField;
    }
}

private bool _ReferenceScriptLibrariesField;

/// <summary>
/// Access the ReferenceScriptLibraries parameter of the template.
/// </summary>
private bool ReferenceScriptLibraries
{
    get
    {
        return this._ReferenceScriptLibrariesField;
    }
}

private bool _IsBundleConfigPresentField;

/// <summary>
/// Access the IsBundleConfigPresent parameter of the template.
/// </summary>
private bool IsBundleConfigPresent
{
    get
    {
        return this._IsBundleConfigPresentField;
    }
}

private string _ViewNameField;

/// <summary>
/// Access the ViewName parameter of the template.
/// </summary>
private string ViewName
{
    get
    {
        return this._ViewNameField;
    }
}

private string _LayoutPageFileField;

/// <summary>
/// Access the LayoutPageFile parameter of the template.
/// </summary>
private string LayoutPageFile
{
    get
    {
        return this._LayoutPageFileField;
    }
}

private string _JQueryVersionField;

/// <summary>
/// Access the JQueryVersion parameter of the template.
/// </summary>
private string JQueryVersion
{
    get
    {
        return this._JQueryVersionField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public override void Initialize()
{
    base.Initialize();
    if ((this.Errors.HasErrors == false))
    {
bool ItemValueAcquired = false;
if (this.Session.ContainsKey("Item"))
{
    this._ItemField = ((global::MannFramework.Application.Item)(this.Session["Item"]));
    ItemValueAcquired = true;
}
if ((ItemValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Item");
    if ((data != null))
    {
        this._ItemField = ((global::MannFramework.Application.Item)(data));
    }
}
bool ItemInRowCountValueAcquired = false;
if (this.Session.ContainsKey("ItemInRowCount"))
{
    this._ItemInRowCountField = ((int)(this.Session["ItemInRowCount"]));
    ItemInRowCountValueAcquired = true;
}
if ((ItemInRowCountValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("ItemInRowCount");
    if ((data != null))
    {
        this._ItemInRowCountField = ((int)(data));
    }
}
bool GenerateMvcModelValueAcquired = false;
if (this.Session.ContainsKey("GenerateMvcModel"))
{
    this._GenerateMvcModelField = ((bool)(this.Session["GenerateMvcModel"]));
    GenerateMvcModelValueAcquired = true;
}
if ((GenerateMvcModelValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("GenerateMvcModel");
    if ((data != null))
    {
        this._GenerateMvcModelField = ((bool)(data));
    }
}
bool UseAngular2ValueAcquired = false;
if (this.Session.ContainsKey("UseAngular2"))
{
    this._UseAngular2Field = ((bool)(this.Session["UseAngular2"]));
    UseAngular2ValueAcquired = true;
}
if ((UseAngular2ValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("UseAngular2");
    if ((data != null))
    {
        this._UseAngular2Field = ((bool)(data));
    }
}
bool AddSaveLinksToTopValueAcquired = false;
if (this.Session.ContainsKey("AddSaveLinksToTop"))
{
    this._AddSaveLinksToTopField = ((bool)(this.Session["AddSaveLinksToTop"]));
    AddSaveLinksToTopValueAcquired = true;
}
if ((AddSaveLinksToTopValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("AddSaveLinksToTop");
    if ((data != null))
    {
        this._AddSaveLinksToTopField = ((bool)(data));
    }
}
bool AddSaveLinksToBottomValueAcquired = false;
if (this.Session.ContainsKey("AddSaveLinksToBottom"))
{
    this._AddSaveLinksToBottomField = ((bool)(this.Session["AddSaveLinksToBottom"]));
    AddSaveLinksToBottomValueAcquired = true;
}
if ((AddSaveLinksToBottomValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("AddSaveLinksToBottom");
    if ((data != null))
    {
        this._AddSaveLinksToBottomField = ((bool)(data));
    }
}
bool ViewDataTypeNameValueAcquired = false;
if (this.Session.ContainsKey("ViewDataTypeName"))
{
    this._ViewDataTypeNameField = ((string)(this.Session["ViewDataTypeName"]));
    ViewDataTypeNameValueAcquired = true;
}
if ((ViewDataTypeNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("ViewDataTypeName");
    if ((data != null))
    {
        this._ViewDataTypeNameField = ((string)(data));
    }
}
bool ViewDataTypeShortNameValueAcquired = false;
if (this.Session.ContainsKey("ViewDataTypeShortName"))
{
    this._ViewDataTypeShortNameField = ((string)(this.Session["ViewDataTypeShortName"]));
    ViewDataTypeShortNameValueAcquired = true;
}
if ((ViewDataTypeShortNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("ViewDataTypeShortName");
    if ((data != null))
    {
        this._ViewDataTypeShortNameField = ((string)(data));
    }
}
bool IsPartialViewValueAcquired = false;
if (this.Session.ContainsKey("IsPartialView"))
{
    this._IsPartialViewField = ((bool)(this.Session["IsPartialView"]));
    IsPartialViewValueAcquired = true;
}
if ((IsPartialViewValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("IsPartialView");
    if ((data != null))
    {
        this._IsPartialViewField = ((bool)(data));
    }
}
bool IsLayoutPageSelectedValueAcquired = false;
if (this.Session.ContainsKey("IsLayoutPageSelected"))
{
    this._IsLayoutPageSelectedField = ((bool)(this.Session["IsLayoutPageSelected"]));
    IsLayoutPageSelectedValueAcquired = true;
}
if ((IsLayoutPageSelectedValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("IsLayoutPageSelected");
    if ((data != null))
    {
        this._IsLayoutPageSelectedField = ((bool)(data));
    }
}
bool ReferenceScriptLibrariesValueAcquired = false;
if (this.Session.ContainsKey("ReferenceScriptLibraries"))
{
    this._ReferenceScriptLibrariesField = ((bool)(this.Session["ReferenceScriptLibraries"]));
    ReferenceScriptLibrariesValueAcquired = true;
}
if ((ReferenceScriptLibrariesValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("ReferenceScriptLibraries");
    if ((data != null))
    {
        this._ReferenceScriptLibrariesField = ((bool)(data));
    }
}
bool IsBundleConfigPresentValueAcquired = false;
if (this.Session.ContainsKey("IsBundleConfigPresent"))
{
    this._IsBundleConfigPresentField = ((bool)(this.Session["IsBundleConfigPresent"]));
    IsBundleConfigPresentValueAcquired = true;
}
if ((IsBundleConfigPresentValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("IsBundleConfigPresent");
    if ((data != null))
    {
        this._IsBundleConfigPresentField = ((bool)(data));
    }
}
bool ViewNameValueAcquired = false;
if (this.Session.ContainsKey("ViewName"))
{
    this._ViewNameField = ((string)(this.Session["ViewName"]));
    ViewNameValueAcquired = true;
}
if ((ViewNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("ViewName");
    if ((data != null))
    {
        this._ViewNameField = ((string)(data));
    }
}
bool LayoutPageFileValueAcquired = false;
if (this.Session.ContainsKey("LayoutPageFile"))
{
    this._LayoutPageFileField = ((string)(this.Session["LayoutPageFile"]));
    LayoutPageFileValueAcquired = true;
}
if ((LayoutPageFileValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("LayoutPageFile");
    if ((data != null))
    {
        this._LayoutPageFileField = ((string)(data));
    }
}
bool JQueryVersionValueAcquired = false;
if (this.Session.ContainsKey("JQueryVersion"))
{
    this._JQueryVersionField = ((string)(this.Session["JQueryVersion"]));
    JQueryVersionValueAcquired = true;
}
if ((JQueryVersionValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("JQueryVersion");
    if ((data != null))
    {
        this._JQueryVersionField = ((string)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
