// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Garcia.CodeGenerator.Template
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using MannFramework;
    using MannFramework.Application;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\ProviderTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class ProviderTemplate : BaseTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("/*\r\n\tThis file was generated automatically by MannFramework Framework. \r\n\tDo not " +
                    "edit manually. \r\n\tAdd a new partial class with the same name if you want to add " +
                    "extra functionality.\r\n*/");
            this.Write("\r\n");
            this.Write("using System;\r\nusing System.Collections.Generic;\r\nusing System.Data;\r\nusing Syste" +
                    "m.Linq;\r\nusing System.ComponentModel.DataAnnotations;\r\n");
            
            #line 9 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\IncludeUsings.t4"
if(FrameworkType == FrameworkType.MannFramework) { 
            
            #line default
            #line hidden
            this.Write("using MannFramework;\r\n");
            
            #line 11 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\IncludeUsings.t4"
} 
            
            #line default
            #line hidden
            this.Write("  \r\n\r\nnamespace ");
            
            #line 19 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\ProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n\t[Serializable]\r\n\tpublic partial class ");
            
            #line 22 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\ProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Item.Name));
            
            #line default
            #line hidden
            this.Write("Provider : ");
            
            #line 22 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\ProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(BaseClass));
            
            #line default
            #line hidden
            this.Write("<");
            
            #line 22 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\ProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Item.Name));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 22 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\ProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Item.Name));
            
            #line default
            #line hidden
            this.Write("Provider>\r\n\t{\r\n\t\tpublic ");
            
            #line 24 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\ProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Item.Name));
            
            #line default
            #line hidden
            this.Write("Provider()\r\n\t\t{\r\n\t\t\tthis.EnableCaching = ");
            
            #line 26 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\ProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(EnableCaching.ToString().ToLower()));
            
            #line default
            #line hidden
            this.Write(";\r\n\t\t}\r\n");
            
            #line 28 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\ProviderTemplate.tt"
if(GenerateCreateEntity) { 
            
            #line default
            #line hidden
            this.Write("\t\t\r\n\t\tprotected override Entity<int> CreateEntity(Dictionary<string, object> data" +
                    "Item, Type entityType)\r\n        {\r\n            return new ");
            
            #line 32 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\ProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Item.Name));
            
            #line default
            #line hidden
            this.Write("();\r\n        }\r\n");
            
            #line 34 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\ProviderTemplate.tt"
} 
            
            #line default
            #line hidden
            
            #line 35 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\ProviderTemplate.tt"
if(GenerateInitializeEntity) { 
            
            #line default
            #line hidden
            this.Write("\r\n\t\tprotected override void InitializeEntity(");
            
            #line 37 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\ProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Item.Name));
            
            #line default
            #line hidden
            this.Write(" entity, Dictionary<string, object> values, bool useAlias)\r\n        {\r\n");
            
            #line 39 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\ProviderTemplate.tt"
 if (this.UseAlias) { 
            
            #line default
            #line hidden
            this.Write("\t\t\tentity.Id = values.GetValue<int>(\"");
            
            #line 40 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\ProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Item.Name));
            
            #line default
            #line hidden
            this.Write(".Id\");\r\n\t\t\tentity.InsertTime = values.GetValue<DateTime>(\"");
            
            #line 41 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\ProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Item.Name));
            
            #line default
            #line hidden
            this.Write(".InsertTime\");\r\n");
            
            #line 42 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\ProviderTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 43 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\ProviderTemplate.tt"
 else { 
            
            #line default
            #line hidden
            this.Write("\t\t\tbase.InitializeEntity(entity, values);\r\n");
            
            #line 45 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\ProviderTemplate.tt"
 } 
            
            #line default
            #line hidden
            
            #line 46 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\ProviderTemplate.tt"

			foreach (var property in Item.Properties)
			{
				string innerTypeName = this.generator.GetInnerTypeName(property);
				string initializeCode = this.GetInitializeCode(Item, property);

            
            #line default
            #line hidden
            this.Write("\t\t\tentity.");
            
            #line 52 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\ProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" = ");
            
            #line 52 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\ProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(initializeCode));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 53 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\ProviderTemplate.tt"

			} 

            
            #line default
            #line hidden
            this.Write("\t\t}\r\n");
            
            #line 57 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\ProviderTemplate.tt"
} 
            
            #line default
            #line hidden
            
            #line 58 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\ProviderTemplate.tt"
if(GenerateGetCommonParameters) { 
            
            #line default
            #line hidden
            this.Write("\r\n\t\tprotected override Dictionary<string, object> GetCommonParameters(");
            
            #line 60 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\ProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Item.Name));
            
            #line default
            #line hidden
            this.Write(" entity)\r\n        {\r\n            Dictionary<string, object> parameters = base.Get" +
                    "CommonParameters(entity);\r\n");
            
            #line 63 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\ProviderTemplate.tt"

			foreach (var property in Item.Properties)
			{
				string innerTypeName = this.generator.GetInnerTypeName(property);
				string commonParameterCode = this.GetCommonParameterCode(Item, property);

            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 69 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\ProviderTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(commonParameterCode));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 70 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\ProviderTemplate.tt"

			} 

            
            #line default
            #line hidden
            this.Write("            return parameters;\r\n        }\r\n");
            
            #line 75 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\ProviderTemplate.tt"
} 
            
            #line default
            #line hidden
            this.Write("\t}\r\n}\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 79 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\ProviderTemplate.tt"

	protected override Generator CreateGenerator()
	{
		return new EntityGenerator();
	}

	protected string GetInitializeCode(Item item, ItemProperty property)
    {
        string text = "";
		string innerType = this.generator.GetInnerTypeName(property);
		string propertyName = property.Name;

		if(this.UseAlias)
		{
			propertyName = item.Name + "." + propertyName;
		}

        switch (property.MappingType)
        {
            case ItemPropertyMappingType.Property:
				if (property.Type == ItemPropertyType.Class)
                {
					string getValuesCode = "values.GetValue<int>(\"" + propertyName + "Id\")";
					text = "EntityManager.Instance.GetItem<" + innerType + ">(" + getValuesCode + ")"; 
				}
				else
				{
					text = "values.GetValue<" + innerType + ">(\"" + propertyName + "\")";
				}
				break;
			case ItemPropertyMappingType.List:
				string itemName = item.Name;
				
				if(this.UseAlias)
				{
					itemName = item.Name + "." + itemName;
				}

                text = "EntityManager.Instance.GetItems<" + innerType + ">(\"" + itemName + "Id\", Entity.Id)"; 
                break;
            case ItemPropertyMappingType.Array:
                // TODO
                break;
			default:
				break;
        }

        return text;
    }

	protected string GetCommonParameterCode(Item item, ItemProperty property)
	{
		return "// TODO";
	}

        
        #line default
        #line hidden
        
        #line 1 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\ProviderTemplate.tt"

private global::MannFramework.Application.Item _ItemField;

/// <summary>
/// Access the Item parameter of the template.
/// </summary>
private global::MannFramework.Application.Item Item
{
    get
    {
        return this._ItemField;
    }
}

private bool _EnableCachingField;

/// <summary>
/// Access the EnableCaching parameter of the template.
/// </summary>
private bool EnableCaching
{
    get
    {
        return this._EnableCachingField;
    }
}

private bool _GenerateCreateEntityField;

/// <summary>
/// Access the GenerateCreateEntity parameter of the template.
/// </summary>
private bool GenerateCreateEntity
{
    get
    {
        return this._GenerateCreateEntityField;
    }
}

private bool _GenerateInitializeEntityField;

/// <summary>
/// Access the GenerateInitializeEntity parameter of the template.
/// </summary>
private bool GenerateInitializeEntity
{
    get
    {
        return this._GenerateInitializeEntityField;
    }
}

private bool _GenerateGetCommonParametersField;

/// <summary>
/// Access the GenerateGetCommonParameters parameter of the template.
/// </summary>
private bool GenerateGetCommonParameters
{
    get
    {
        return this._GenerateGetCommonParametersField;
    }
}

private bool _UseAliasField;

/// <summary>
/// Access the UseAlias parameter of the template.
/// </summary>
private bool UseAlias
{
    get
    {
        return this._UseAliasField;
    }
}

private string _BaseClassField;

/// <summary>
/// Access the BaseClass parameter of the template.
/// </summary>
private string BaseClass
{
    get
    {
        return this._BaseClassField;
    }
}

private string _NamespaceField;

/// <summary>
/// Access the Namespace parameter of the template.
/// </summary>
private string Namespace
{
    get
    {
        return this._NamespaceField;
    }
}

private global::MannFramework.Application.FrameworkType _FrameworkTypeField;

/// <summary>
/// Access the FrameworkType parameter of the template.
/// </summary>
private global::MannFramework.Application.FrameworkType FrameworkType
{
    get
    {
        return this._FrameworkTypeField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public override void Initialize()
{
    base.Initialize();
    if ((this.Errors.HasErrors == false))
    {
bool ItemValueAcquired = false;
if (this.Session.ContainsKey("Item"))
{
    this._ItemField = ((global::MannFramework.Application.Item)(this.Session["Item"]));
    ItemValueAcquired = true;
}
if ((ItemValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Item");
    if ((data != null))
    {
        this._ItemField = ((global::MannFramework.Application.Item)(data));
    }
}
bool EnableCachingValueAcquired = false;
if (this.Session.ContainsKey("EnableCaching"))
{
    this._EnableCachingField = ((bool)(this.Session["EnableCaching"]));
    EnableCachingValueAcquired = true;
}
if ((EnableCachingValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("EnableCaching");
    if ((data != null))
    {
        this._EnableCachingField = ((bool)(data));
    }
}
bool GenerateCreateEntityValueAcquired = false;
if (this.Session.ContainsKey("GenerateCreateEntity"))
{
    this._GenerateCreateEntityField = ((bool)(this.Session["GenerateCreateEntity"]));
    GenerateCreateEntityValueAcquired = true;
}
if ((GenerateCreateEntityValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("GenerateCreateEntity");
    if ((data != null))
    {
        this._GenerateCreateEntityField = ((bool)(data));
    }
}
bool GenerateInitializeEntityValueAcquired = false;
if (this.Session.ContainsKey("GenerateInitializeEntity"))
{
    this._GenerateInitializeEntityField = ((bool)(this.Session["GenerateInitializeEntity"]));
    GenerateInitializeEntityValueAcquired = true;
}
if ((GenerateInitializeEntityValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("GenerateInitializeEntity");
    if ((data != null))
    {
        this._GenerateInitializeEntityField = ((bool)(data));
    }
}
bool GenerateGetCommonParametersValueAcquired = false;
if (this.Session.ContainsKey("GenerateGetCommonParameters"))
{
    this._GenerateGetCommonParametersField = ((bool)(this.Session["GenerateGetCommonParameters"]));
    GenerateGetCommonParametersValueAcquired = true;
}
if ((GenerateGetCommonParametersValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("GenerateGetCommonParameters");
    if ((data != null))
    {
        this._GenerateGetCommonParametersField = ((bool)(data));
    }
}
bool UseAliasValueAcquired = false;
if (this.Session.ContainsKey("UseAlias"))
{
    this._UseAliasField = ((bool)(this.Session["UseAlias"]));
    UseAliasValueAcquired = true;
}
if ((UseAliasValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("UseAlias");
    if ((data != null))
    {
        this._UseAliasField = ((bool)(data));
    }
}
bool BaseClassValueAcquired = false;
if (this.Session.ContainsKey("BaseClass"))
{
    this._BaseClassField = ((string)(this.Session["BaseClass"]));
    BaseClassValueAcquired = true;
}
if ((BaseClassValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("BaseClass");
    if ((data != null))
    {
        this._BaseClassField = ((string)(data));
    }
}
bool NamespaceValueAcquired = false;
if (this.Session.ContainsKey("Namespace"))
{
    this._NamespaceField = ((string)(this.Session["Namespace"]));
    NamespaceValueAcquired = true;
}
if ((NamespaceValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Namespace");
    if ((data != null))
    {
        this._NamespaceField = ((string)(data));
    }
}
bool FrameworkTypeValueAcquired = false;
if (this.Session.ContainsKey("FrameworkType"))
{
    this._FrameworkTypeField = ((global::MannFramework.Application.FrameworkType)(this.Session["FrameworkType"]));
    FrameworkTypeValueAcquired = true;
}
if ((FrameworkTypeValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("FrameworkType");
    if ((data != null))
    {
        this._FrameworkTypeField = ((global::MannFramework.Application.FrameworkType)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
