// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Garcia.CodeGenerator.Template
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using MannFramework;
    using MannFramework.Application;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiModelTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class WebApiModelTemplate : BaseTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("/*\r\n\tThis file was generated automatically by MannFramework Framework. \r\n\tDo not " +
                    "edit manually. \r\n\tAdd a new partial class with the same name if you want to add " +
                    "extra functionality.\r\n*/");
            this.Write("\r\n");
            this.Write("using System;\r\nusing System.Collections.Generic;\r\nusing System.Data;\r\nusing Syste" +
                    "m.Linq;\r\nusing System.ComponentModel.DataAnnotations;\r\n");
            
            #line 9 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\IncludeUsings.t4"
if(FrameworkType == FrameworkType.MannFramework) { 
            
            #line default
            #line hidden
            this.Write("using MannFramework;\r\n");
            
            #line 11 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\IncludeUsings.t4"
} 
            
            #line default
            #line hidden
            
            #line 14 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiModelTemplate.tt"

	List<ItemProperty> properties = Item.Properties.Where(x => x.AccessorType == AccessorType.Public).ToList();

            
            #line default
            #line hidden
            this.Write("using ");
            
            #line 17 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Item.ProjectName));
            
            #line default
            #line hidden
            this.Write(".BL;\r\n\r\nnamespace ");
            
            #line 19 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n\tpublic partial class ");
            
            #line 21 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Item.Name));
            
            #line default
            #line hidden
            this.Write("Model : ");
            
            #line 21 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(BaseClass));
            
            #line default
            #line hidden
            this.Write("<");
            
            #line 21 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Item.Name));
            
            #line default
            #line hidden
            this.Write(">\r\n\t{\r\n");
            
            #line 23 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiModelTemplate.tt"
 
		foreach (var property in properties)
		{
			string innerTypeName = this.generator.GetInnerTypeName(property); 

            
            #line default
            #line hidden
            this.Write("\t\tpublic ");
            
            #line 28 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(innerTypeName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 28 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" { get; set; }\r\n");
            
            #line 29 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiModelTemplate.tt"
 
		} 

            
            #line default
            #line hidden
            this.Write("\r\n\t\tpublic ");
            
            #line 33 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Item.Name));
            
            #line default
            #line hidden
            this.Write("Model()\r\n\t\t{\r\n");
            
            #line 35 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiModelTemplate.tt"
 
			foreach (var property in properties)
			{
				string innerTypeName = this.generator.GetInnerTypeName(property);
				
				switch (property.MappingType)
                {
                    case ItemPropertyMappingType.Property:
                        break;
                    case ItemPropertyMappingType.List: 

            
            #line default
            #line hidden
            this.Write("\t\t\tthis.");
            
            #line 46 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" = new ");
            
            #line 46 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(innerTypeName));
            
            #line default
            #line hidden
            this.Write(" ();\r\n");
            
            #line 47 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiModelTemplate.tt"
						break;
                    case ItemPropertyMappingType.Array:
                        // TODO
                        break;
                }
			} 

            
            #line default
            #line hidden
            this.Write("\t\t}\r\n\r\n\t\tpublic ");
            
            #line 56 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Item.Name));
            
            #line default
            #line hidden
            this.Write("Model(");
            
            #line 56 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Item.Name));
            
            #line default
            #line hidden
            this.Write(" item) : base(item)\r\n\t\t{\r\n");
            
            #line 58 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiModelTemplate.tt"
 
			foreach (var property in properties)
			{
				string innerTypeName = this.generator.GetInnerTypeName(property);
				
				switch (property.MappingType)
                {
                    case ItemPropertyMappingType.Property:
			if (property.InnerType != null && property.Type != ItemPropertyType.Enum)
			{

            
            #line default
            #line hidden
            this.Write("\t\t\tthis.");
            
            #line 69 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" = Model.GetModel<");
            
            #line 69 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.InnerType.Name));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 69 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.InnerType.Name));
            
            #line default
            #line hidden
            this.Write("Model>(item.");
            
            #line 69 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 70 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiModelTemplate.tt"

			}
			else
			{

            
            #line default
            #line hidden
            this.Write("\t\t\tthis.");
            
            #line 75 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" = item.");
            
            #line 75 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 76 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiModelTemplate.tt"

			}
						break;
                    case ItemPropertyMappingType.List: 
			if (property.InnerType != null && property.Type != ItemPropertyType.Enum)
			{

            
            #line default
            #line hidden
            this.Write("\t\t\tthis.");
            
            #line 83 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" = Model.GetModels<");
            
            #line 83 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.InnerType.Name));
            
            #line default
            #line hidden
            this.Write(", ");
            
            #line 83 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.InnerType.Name));
            
            #line default
            #line hidden
            this.Write("Model>(item.");
            
            #line 83 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 84 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiModelTemplate.tt"

			}
			else
			{

            
            #line default
            #line hidden
            this.Write("\t\t\tthis.");
            
            #line 89 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(" = item.");
            
            #line 89 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiModelTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(";\r\n");
            
            #line 90 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiModelTemplate.tt"

			}
						break;
                    case ItemPropertyMappingType.Array:
                        // TODO
                        break;
                }
			} 

            
            #line default
            #line hidden
            this.Write("\t\t}\r\n\t}\r\n}\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 103 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiModelTemplate.tt"

	protected override Generator CreateGenerator()
	{
		return new WebApiModelGenerator();
	}

        
        #line default
        #line hidden
        
        #line 1 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiModelTemplate.tt"

private global::MannFramework.Application.Item _ItemField;

/// <summary>
/// Access the Item parameter of the template.
/// </summary>
private global::MannFramework.Application.Item Item
{
    get
    {
        return this._ItemField;
    }
}

private string _BaseClassField;

/// <summary>
/// Access the BaseClass parameter of the template.
/// </summary>
private string BaseClass
{
    get
    {
        return this._BaseClassField;
    }
}

private string _WebApiModelNamespaceSuffixField;

/// <summary>
/// Access the WebApiModelNamespaceSuffix parameter of the template.
/// </summary>
private string WebApiModelNamespaceSuffix
{
    get
    {
        return this._WebApiModelNamespaceSuffixField;
    }
}

private string _NamespaceField;

/// <summary>
/// Access the Namespace parameter of the template.
/// </summary>
private string Namespace
{
    get
    {
        return this._NamespaceField;
    }
}

private global::MannFramework.Application.FrameworkType _FrameworkTypeField;

/// <summary>
/// Access the FrameworkType parameter of the template.
/// </summary>
private global::MannFramework.Application.FrameworkType FrameworkType
{
    get
    {
        return this._FrameworkTypeField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public override void Initialize()
{
    base.Initialize();
    if ((this.Errors.HasErrors == false))
    {
bool ItemValueAcquired = false;
if (this.Session.ContainsKey("Item"))
{
    this._ItemField = ((global::MannFramework.Application.Item)(this.Session["Item"]));
    ItemValueAcquired = true;
}
if ((ItemValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Item");
    if ((data != null))
    {
        this._ItemField = ((global::MannFramework.Application.Item)(data));
    }
}
bool BaseClassValueAcquired = false;
if (this.Session.ContainsKey("BaseClass"))
{
    this._BaseClassField = ((string)(this.Session["BaseClass"]));
    BaseClassValueAcquired = true;
}
if ((BaseClassValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("BaseClass");
    if ((data != null))
    {
        this._BaseClassField = ((string)(data));
    }
}
bool WebApiModelNamespaceSuffixValueAcquired = false;
if (this.Session.ContainsKey("WebApiModelNamespaceSuffix"))
{
    this._WebApiModelNamespaceSuffixField = ((string)(this.Session["WebApiModelNamespaceSuffix"]));
    WebApiModelNamespaceSuffixValueAcquired = true;
}
if ((WebApiModelNamespaceSuffixValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("WebApiModelNamespaceSuffix");
    if ((data != null))
    {
        this._WebApiModelNamespaceSuffixField = ((string)(data));
    }
}
bool NamespaceValueAcquired = false;
if (this.Session.ContainsKey("Namespace"))
{
    this._NamespaceField = ((string)(this.Session["Namespace"]));
    NamespaceValueAcquired = true;
}
if ((NamespaceValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Namespace");
    if ((data != null))
    {
        this._NamespaceField = ((string)(data));
    }
}
bool FrameworkTypeValueAcquired = false;
if (this.Session.ContainsKey("FrameworkType"))
{
    this._FrameworkTypeField = ((global::MannFramework.Application.FrameworkType)(this.Session["FrameworkType"]));
    FrameworkTypeValueAcquired = true;
}
if ((FrameworkTypeValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("FrameworkType");
    if ((data != null))
    {
        this._FrameworkTypeField = ((global::MannFramework.Application.FrameworkType)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
