// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 17.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Garcia.CodeGenerator.Template
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using MannFramework;
    using MannFramework.Application;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiControllerTemplate.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "17.0.0.0")]
    public partial class WebApiControllerTemplate : BaseTemplate
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public override string TransformText()
        {
            this.Write("/*\r\n\tThis file was generated automatically by MannFramework Framework. \r\n\tDo not " +
                    "edit manually. \r\n\tAdd a new partial class with the same name if you want to add " +
                    "extra functionality.\r\n*/");
            this.Write("\r\n");
            this.Write("using System;\r\nusing System.Collections.Generic;\r\nusing System.Data;\r\nusing Syste" +
                    "m.Linq;\r\nusing System.ComponentModel.DataAnnotations;\r\n");
            
            #line 9 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\IncludeUsings.t4"
if(FrameworkType == FrameworkType.MannFramework) { 
            
            #line default
            #line hidden
            this.Write("using MannFramework;\r\n");
            
            #line 11 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\IncludeUsings.t4"
} 
            
            #line default
            #line hidden
            this.Write("  \r\n");
            
            #line 21 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiControllerTemplate.tt"

	string itemName = Item.Name;
	string modelName = itemName;

	if (GenerateWebApiModel)
	{
		modelName += "Model";
	}

	string controllerName = itemName + "Controller";
	List<ItemProperty> properties = Item.Properties.Where(x => x.AccessorType == AccessorType.Public).ToList();
	string className = "public partial class " + itemName + "Controller : " + BaseWebApiControllerName + "<" + itemName;
	string modelParameterName = "item";
	
	if (GenerateWebApiModel)
	{
		className += (", " + modelName);
		modelParameterName = "model";
	}
	
	className += ">";
	Dictionary<string, int> generatedMethods = new Dictionary<string, int>();

            
            #line default
            #line hidden
            this.Write("using System.Web.Http;\r\n");
            
            #line 45 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Includes));
            
            #line default
            #line hidden
            this.Write("\r\nnamespace ");
            
            #line 46 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Namespace));
            
            #line default
            #line hidden
            this.Write("\r\n{\r\n\t");
            
            #line 48 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(className));
            
            #line default
            #line hidden
            this.Write("\r\n\t{\r\n");
            
            #line 50 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiControllerTemplate.tt"
if(GenerateWebApiGetOne) { 
            
            #line default
            #line hidden
            this.Write("\t\tpublic override MannFrameworkHttpResponseMessage<");
            
            #line 51 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelName));
            
            #line default
            #line hidden
            this.Write("> Get(int id)\r\n        {\r\n            MannFrameworkHttpResponseMessage<");
            
            #line 53 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelName));
            
            #line default
            #line hidden
            this.Write("> model = this.GetModel(id);\r\n            return model;\r\n        }\r\n\r\n");
            
            #line 57 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiControllerTemplate.tt"
} 
            
            #line default
            #line hidden
            
            #line 58 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiControllerTemplate.tt"
if(GenerateWebApiGetAll) { 
            
            #line default
            #line hidden
            this.Write("\t\tpublic override MannFrameworkHttpResponseMessage<List<");
            
            #line 59 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelName));
            
            #line default
            #line hidden
            this.Write(">> Get()\r\n        {\r\n            MannFrameworkHttpResponseMessage<List<");
            
            #line 61 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelName));
            
            #line default
            #line hidden
            this.Write(">> models = this.GetModels();\r\n            return models;\r\n        }\r\n\r\n");
            
            #line 65 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiControllerTemplate.tt"
} 
            
            #line default
            #line hidden
            
            #line 66 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiControllerTemplate.tt"
if(GenerateWebApiPost) { 
            
            #line default
            #line hidden
            this.Write("\t\tpublic override MannFrameworkHttpResponseMessage Post([FromBody]");
            
            #line 67 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelName));
            
            #line default
            #line hidden
            this.Write(" ");
            
            #line 67 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelParameterName));
            
            #line default
            #line hidden
            this.Write(")\r\n        {\r\n");
            
            #line 69 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiControllerTemplate.tt"
if(GenerateWebApiModel) { 
            
            #line default
            #line hidden
            this.Write("            ");
            
            #line 70 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(itemName));
            
            #line default
            #line hidden
            this.Write(" item = model.ToEntity();\r\n");
            
            #line 71 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiControllerTemplate.tt"
} 
            
            #line default
            #line hidden
            this.Write(@"            if (item == null)
            {
                return new MannFrameworkHttpResponseMessage(System.Net.HttpStatusCode.NotFound);
            }

            OperationResult saveResult = EntityManager.Instance.Save(item);
            return new MannFrameworkHttpResponseMessage(saveResult);
        }

");
            
            #line 81 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiControllerTemplate.tt"
} 
            
            #line default
            #line hidden
            
            #line 82 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiControllerTemplate.tt"
if(GenerateWebApiDelete) { 
            
            #line default
            #line hidden
            this.Write("\t\tpublic override MannFrameworkHttpResponseMessage<");
            
            #line 83 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelName));
            
            #line default
            #line hidden
            this.Write("> Delete(int id)\r\n        {\r\n            ");
            
            #line 85 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(itemName));
            
            #line default
            #line hidden
            this.Write(" entity = EntityManager.Instance.GetItem <");
            
            #line 85 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(itemName));
            
            #line default
            #line hidden
            this.Write(">(id);\r\n            entity.IsMarkedForDeletion = true;\r\n            OperationResu" +
                    "lt result = EntityManager.Instance.Save(entity);\r\n            return new MannFra" +
                    "meworkHttpResponseMessage<");
            
            #line 88 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(modelName));
            
            #line default
            #line hidden
            this.Write(">(result);\r\n        }\r\n");
            
            #line 90 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiControllerTemplate.tt"
} 
            
            #line default
            #line hidden
            
            #line 91 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiControllerTemplate.tt"
 
if (!GenerateWebApiModel)
{
	Action<Item, string, List<Item>, List<ItemProperty>> IterateThroughChildren = null; 
    IterateThroughChildren = delegate(Item item, string basePath, List<Item> items, List<ItemProperty> parameterProperties)
    {
		List<ItemProperty> innerProperties = item.Properties.Where(x => x.AccessorType == AccessorType.Public).ToList();
		string innerItemName = item.Name;
		string path = "api/";
		
		foreach (ItemProperty property in innerProperties.Where(x => x.Type == ItemPropertyType.Class && x.MappingType == ItemPropertyMappingType.List))
		{
			string innerTypeName = this.generator.GetInnerTypeName(property); 
			basePath = basePath + "/";
			string parameters = "";
			string parameter = "";
			string parameterName = "";
			int counter = 0;
			List<string> parameterNames = new List<string>();

			foreach(Item tempItem in items)
			{
				path += tempItem.Name + "/";

				if (counter == 0)
				{
					parameter = ("int id");
					parameterName = "{id}";
					// parameterNames.Add("id");
				}
				else
				{
					parameter = (", int " + tempItem.Name.ToPascalCase() + "Id");
					parameterName = "{" + tempItem.Name.ToPascalCase() + "Id}";
					parameterNames.Add(tempItem.Name.ToPascalCase() + "Id");
				}

				parameters += parameter;
				path += parameterName + "/";
				counter++;
			}

			// path += item.Name + "/";
			path += item.Name + "/" + property.Name + "/";

			if (counter == 0)
			{
				parameter = ("int id");
				parameterName = "{id}";
				// parameterNames.Add("id");
			}
			else
			{
				parameter = (", int " + item.Name.ToPascalCase() + "Id");
				parameterName = "{" + item.Name.ToPascalCase() + "Id}";
				parameterNames.Add(item.Name.ToPascalCase() + "Id");
			}

			parameters += parameter;
			path += parameterName + "/";
			string methodName = GetMethodName(generatedMethods, "Get" + property.Name);

            
            #line default
            #line hidden
            this.Write("\t\t[Route(\"");
            
            #line 153 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(path));
            
            #line default
            #line hidden
            this.Write("\")]\r\n\t\tpublic MannFrameworkHttpResponseMessage<");
            
            #line 154 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(innerTypeName));
            
            #line default
            #line hidden
            this.Write("> ");
            
            #line 154 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(methodName));
            
            #line default
            #line hidden
            this.Write("(");
            
            #line 154 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(parameters));
            
            #line default
            #line hidden
            this.Write(")\r\n\t\t{\r\n");
            
            #line 156 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiControllerTemplate.tt"
 if (items.Count != 0) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 157 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(items[0].Name));
            
            #line default
            #line hidden
            this.Write(" entity = EntityManager.Instance.GetItem<");
            
            #line 157 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(items[0].Name));
            
            #line default
            #line hidden
            this.Write(">(id);\r\n");
            
            #line 158 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiControllerTemplate.tt"
 
			string name = "";
			string name2 = "";
			counter = 0;

			foreach (Item innerItem in items)
			{
				if (counter == 0)
				{
					continue;
				}

				name += innerItem.Name + ".";
				counter++;
			}

			name += item.Name + "?." + property.Name;
			counter = 0;

			foreach (ItemProperty innerProperty in parameterProperties)
			{
				// name2 += innerProperty.Name + ".Single(x => x.Id == " + parameterName.Trim('{').Trim('}') + ").";
				name2 += innerProperty.Name + "?.FirstOrDefault(x => x.Id == " + parameterNames[counter] + ")?.";
				counter++;
			}

			name2 += property.Name;

            
            #line default
            #line hidden
            this.Write("\t\t\tMannFrameworkHttpResponseMessage<");
            
            #line 186 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(innerTypeName));
            
            #line default
            #line hidden
            this.Write("> item = new MannFrameworkHttpResponseMessage<");
            
            #line 186 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(innerTypeName));
            
            #line default
            #line hidden
            this.Write(">(entity.");
            
            #line 186 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(name2));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 187 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiControllerTemplate.tt"
 } else { 
            
            #line default
            #line hidden
            this.Write("\t\t\t");
            
            #line 188 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(innerItemName));
            
            #line default
            #line hidden
            this.Write(" entity = EntityManager.Instance.GetItem<");
            
            #line 188 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(innerItemName));
            
            #line default
            #line hidden
            this.Write(">(id);\r\n\t\t\tMannFrameworkHttpResponseMessage<");
            
            #line 189 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(innerTypeName));
            
            #line default
            #line hidden
            this.Write("> item = new MannFrameworkHttpResponseMessage<");
            
            #line 189 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(innerTypeName));
            
            #line default
            #line hidden
            this.Write(">(entity.");
            
            #line 189 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiControllerTemplate.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(property.Name));
            
            #line default
            #line hidden
            this.Write(");\r\n");
            
            #line 190 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiControllerTemplate.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t\treturn item;\r\n\t\t}\r\n\r\n");
            
            #line 194 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiControllerTemplate.tt"
 
			if (property.InnerType != null)
			{
				basePath += (item.Name + "/{id}");
				items.Add(item);
				parameterProperties.Add(property);
				IterateThroughChildren(property.InnerType, basePath, items, parameterProperties);
			}
		}
	};

	IterateThroughChildren(Item, "", new List<Item>() {}, new List<ItemProperty>() {} );
}


            
            #line default
            #line hidden
            this.Write("\t}\r\n}\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 212 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiControllerTemplate.tt"

	protected override Generator CreateGenerator()
	{
		return new WebApiControllerGenerator();
	}

	protected string GetMethodName(Dictionary<string, int> generatedMethods, string methodName)
	{
		if (generatedMethods.ContainsKey(methodName))
		{
			generatedMethods[methodName]++;
			return methodName + "_" + generatedMethods[methodName].ToString();
		}
		else
		{
			generatedMethods.Add(methodName, 0);
			return methodName;
		}
	}

        
        #line default
        #line hidden
        
        #line 1 "C:\Users\vehbi\source\repos\garcia\Garcia.CodeGenerator\Template\WebApiControllerTemplate.tt"

private global::MannFramework.Application.Item _ItemField;

/// <summary>
/// Access the Item parameter of the template.
/// </summary>
private global::MannFramework.Application.Item Item
{
    get
    {
        return this._ItemField;
    }
}

private bool _GenerateWebApiGetOneField;

/// <summary>
/// Access the GenerateWebApiGetOne parameter of the template.
/// </summary>
private bool GenerateWebApiGetOne
{
    get
    {
        return this._GenerateWebApiGetOneField;
    }
}

private bool _GenerateWebApiGetAllField;

/// <summary>
/// Access the GenerateWebApiGetAll parameter of the template.
/// </summary>
private bool GenerateWebApiGetAll
{
    get
    {
        return this._GenerateWebApiGetAllField;
    }
}

private bool _GenerateWebApiPostField;

/// <summary>
/// Access the GenerateWebApiPost parameter of the template.
/// </summary>
private bool GenerateWebApiPost
{
    get
    {
        return this._GenerateWebApiPostField;
    }
}

private bool _GenerateWebApiDeleteField;

/// <summary>
/// Access the GenerateWebApiDelete parameter of the template.
/// </summary>
private bool GenerateWebApiDelete
{
    get
    {
        return this._GenerateWebApiDeleteField;
    }
}

private string _BaseWebApiControllerNameField;

/// <summary>
/// Access the BaseWebApiControllerName parameter of the template.
/// </summary>
private string BaseWebApiControllerName
{
    get
    {
        return this._BaseWebApiControllerNameField;
    }
}

private string _WebApiControllerNamespaceSuffixField;

/// <summary>
/// Access the WebApiControllerNamespaceSuffix parameter of the template.
/// </summary>
private string WebApiControllerNamespaceSuffix
{
    get
    {
        return this._WebApiControllerNamespaceSuffixField;
    }
}

private string _WebApiModelNamespaceSuffixField;

/// <summary>
/// Access the WebApiModelNamespaceSuffix parameter of the template.
/// </summary>
private string WebApiModelNamespaceSuffix
{
    get
    {
        return this._WebApiModelNamespaceSuffixField;
    }
}

private bool _GenerateWebApiModelField;

/// <summary>
/// Access the GenerateWebApiModel parameter of the template.
/// </summary>
private bool GenerateWebApiModel
{
    get
    {
        return this._GenerateWebApiModelField;
    }
}

private string _NamespaceField;

/// <summary>
/// Access the Namespace parameter of the template.
/// </summary>
private string Namespace
{
    get
    {
        return this._NamespaceField;
    }
}

private string _IncludesField;

/// <summary>
/// Access the Includes parameter of the template.
/// </summary>
private string Includes
{
    get
    {
        return this._IncludesField;
    }
}

private global::MannFramework.Application.FrameworkType _FrameworkTypeField;

/// <summary>
/// Access the FrameworkType parameter of the template.
/// </summary>
private global::MannFramework.Application.FrameworkType FrameworkType
{
    get
    {
        return this._FrameworkTypeField;
    }
}


/// <summary>
/// Initialize the template
/// </summary>
public override void Initialize()
{
    base.Initialize();
    if ((this.Errors.HasErrors == false))
    {
bool ItemValueAcquired = false;
if (this.Session.ContainsKey("Item"))
{
    this._ItemField = ((global::MannFramework.Application.Item)(this.Session["Item"]));
    ItemValueAcquired = true;
}
if ((ItemValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Item");
    if ((data != null))
    {
        this._ItemField = ((global::MannFramework.Application.Item)(data));
    }
}
bool GenerateWebApiGetOneValueAcquired = false;
if (this.Session.ContainsKey("GenerateWebApiGetOne"))
{
    this._GenerateWebApiGetOneField = ((bool)(this.Session["GenerateWebApiGetOne"]));
    GenerateWebApiGetOneValueAcquired = true;
}
if ((GenerateWebApiGetOneValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("GenerateWebApiGetOne");
    if ((data != null))
    {
        this._GenerateWebApiGetOneField = ((bool)(data));
    }
}
bool GenerateWebApiGetAllValueAcquired = false;
if (this.Session.ContainsKey("GenerateWebApiGetAll"))
{
    this._GenerateWebApiGetAllField = ((bool)(this.Session["GenerateWebApiGetAll"]));
    GenerateWebApiGetAllValueAcquired = true;
}
if ((GenerateWebApiGetAllValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("GenerateWebApiGetAll");
    if ((data != null))
    {
        this._GenerateWebApiGetAllField = ((bool)(data));
    }
}
bool GenerateWebApiPostValueAcquired = false;
if (this.Session.ContainsKey("GenerateWebApiPost"))
{
    this._GenerateWebApiPostField = ((bool)(this.Session["GenerateWebApiPost"]));
    GenerateWebApiPostValueAcquired = true;
}
if ((GenerateWebApiPostValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("GenerateWebApiPost");
    if ((data != null))
    {
        this._GenerateWebApiPostField = ((bool)(data));
    }
}
bool GenerateWebApiDeleteValueAcquired = false;
if (this.Session.ContainsKey("GenerateWebApiDelete"))
{
    this._GenerateWebApiDeleteField = ((bool)(this.Session["GenerateWebApiDelete"]));
    GenerateWebApiDeleteValueAcquired = true;
}
if ((GenerateWebApiDeleteValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("GenerateWebApiDelete");
    if ((data != null))
    {
        this._GenerateWebApiDeleteField = ((bool)(data));
    }
}
bool BaseWebApiControllerNameValueAcquired = false;
if (this.Session.ContainsKey("BaseWebApiControllerName"))
{
    this._BaseWebApiControllerNameField = ((string)(this.Session["BaseWebApiControllerName"]));
    BaseWebApiControllerNameValueAcquired = true;
}
if ((BaseWebApiControllerNameValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("BaseWebApiControllerName");
    if ((data != null))
    {
        this._BaseWebApiControllerNameField = ((string)(data));
    }
}
bool WebApiControllerNamespaceSuffixValueAcquired = false;
if (this.Session.ContainsKey("WebApiControllerNamespaceSuffix"))
{
    this._WebApiControllerNamespaceSuffixField = ((string)(this.Session["WebApiControllerNamespaceSuffix"]));
    WebApiControllerNamespaceSuffixValueAcquired = true;
}
if ((WebApiControllerNamespaceSuffixValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("WebApiControllerNamespaceSuffix");
    if ((data != null))
    {
        this._WebApiControllerNamespaceSuffixField = ((string)(data));
    }
}
bool WebApiModelNamespaceSuffixValueAcquired = false;
if (this.Session.ContainsKey("WebApiModelNamespaceSuffix"))
{
    this._WebApiModelNamespaceSuffixField = ((string)(this.Session["WebApiModelNamespaceSuffix"]));
    WebApiModelNamespaceSuffixValueAcquired = true;
}
if ((WebApiModelNamespaceSuffixValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("WebApiModelNamespaceSuffix");
    if ((data != null))
    {
        this._WebApiModelNamespaceSuffixField = ((string)(data));
    }
}
bool GenerateWebApiModelValueAcquired = false;
if (this.Session.ContainsKey("GenerateWebApiModel"))
{
    this._GenerateWebApiModelField = ((bool)(this.Session["GenerateWebApiModel"]));
    GenerateWebApiModelValueAcquired = true;
}
if ((GenerateWebApiModelValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("GenerateWebApiModel");
    if ((data != null))
    {
        this._GenerateWebApiModelField = ((bool)(data));
    }
}
bool NamespaceValueAcquired = false;
if (this.Session.ContainsKey("Namespace"))
{
    this._NamespaceField = ((string)(this.Session["Namespace"]));
    NamespaceValueAcquired = true;
}
if ((NamespaceValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Namespace");
    if ((data != null))
    {
        this._NamespaceField = ((string)(data));
    }
}
bool IncludesValueAcquired = false;
if (this.Session.ContainsKey("Includes"))
{
    this._IncludesField = ((string)(this.Session["Includes"]));
    IncludesValueAcquired = true;
}
if ((IncludesValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("Includes");
    if ((data != null))
    {
        this._IncludesField = ((string)(data));
    }
}
bool FrameworkTypeValueAcquired = false;
if (this.Session.ContainsKey("FrameworkType"))
{
    this._FrameworkTypeField = ((global::MannFramework.Application.FrameworkType)(this.Session["FrameworkType"]));
    FrameworkTypeValueAcquired = true;
}
if ((FrameworkTypeValueAcquired == false))
{
    object data = global::System.Runtime.Remoting.Messaging.CallContext.LogicalGetData("FrameworkType");
    if ((data != null))
    {
        this._FrameworkTypeField = ((global::MannFramework.Application.FrameworkType)(data));
    }
}


    }
}


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
}
