/*
	This file was generated automatically by Garcia Framework. 
	Do not edit manually. 
	Add a new partial class with the same name if you want to add extra functionality.
*/
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using MannFramework;
using System.Web.Http.Routing;
using System.Web.Mvc;
using MannFramework.Macondo.BL;
using MannFramework.Application;

namespace MannFramework.Macondo.Controllers
{
    public partial class ItemPropertyController : GarciaEntityMvcController<ItemProperty>
    {
        public ItemPropertyController()
        {
            this.UseAutoGeneratedListView = false;
        }

        protected override bool InnerCheckSession()
        {
            return UIStateManager.Instance.Project != null;
        }

        //protected override bool InnerCheckSession()
        //{
        //    return UIStateManager.Instance.CheckProject();
        //}

        public override ActionResult Edit(int? id)
        {
            return base.Edit(id);
        }

        public override ActionResult List()
        {
            int itemId = Helpers.GetValueFromObject<int>(Request.QueryString["ItemId"]);
            Item item = EntityManager.Instance.GetItem<Item>(itemId);

            if (!item.ProjectId.HasValue)
            {
                return this.RedirectToHome();
            }
            else if (item.ProjectId.Value.ToString() != UIStateManager.Instance.ProjectId)
            {
                UIStateManager.Instance.SelectProject(item.ProjectId.Value);
            }

            string title = item == null ? "" : item.Name + " ";
            ViewBag.PageTitle = title + GarciaLocalizationManager.Localize("ItemPropertyList");
            return base.List();
        }
    }
}

