/*
	This file was generated automatically by Garcia Framework. 
	Do not edit manually. 
	Add a new partial class with the same name if you want to add extra functionality.
*/
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using MannFramework;
using System.Web.Http.Routing;
using System.Web.Mvc;
using MannFramework.Macondo.BL;
using System.Web.Routing;
using MannFramework.Application;

namespace MannFramework.Macondo.Controllers
{
    public partial class ProjectController : GarciaEntityMvcController<Project>
    {
        public ProjectController()
        {
            this.UseAutoGeneratedListView = false;
        }

        [HttpGet]
        public ActionResult Select(int id)
        {
            UIStateManager.Instance.SelectProject(id);
            return RedirectToAction("List", "Item", new RouteValueDictionary() { { "ProjectId", id } });
        }

        protected override void AfterEdit()
        {
            UIStateManager.Instance.RefreshProject();
        }

        [HttpPost]
        public override ActionResult Edit(Project model)
        {
            int id = model.Id;
            ActionResult result = base.Edit(model);

            if (ModelState.IsValid)
            {
                return id == 0 ? new RedirectResult(Url.Action("Edit", new { @Id = model.Id }) + "#settings") : new RedirectResult(Url.Action("Edit", new { @Id = model.Id }));
            }

            return View(model);
        }
    }
}